# Pré-processamento

Em um sistema baseado em Visão Computacional, a etapa de
pré-processamento consiste em realçar objetos de interesse em imagens, facilitando segmentá-los posteriormente. Para realçar esses objetos, existem inúmeros procedimentos que podem ser realizados, como operações aritméticas, operações geométricas, métodos para ajuste de contraste e tratamento de ruído. Vamos conhecer agora algum desses procedimentos.


#### Como você ja deve saber, uma imagem é uma matriz de pixels, em python conseguimos acessa-los com facilmente, veja:

In [4]:
# Primeito irei importar a biblioteca do OpenCV e tentarei ver as dimensões da matriz
import	cv2
import numpy as numpy
imagem = cv2.imread("/home/luiz/Documentos/MeusProjetos/Dicas_OpenCV/VisaoComp/Imagens/frutas3.jpg") # Lendo nossa imagem, lembre de usar esse formato de path se estiver usando o jupyter notebook
print(imagem.shape) # Imprime as dimensões

(810, 1200, 3)


Temos uma imagem de 3456x518 pixels, podemos imprimi-la com os métodos que ja estudamos antes, vamos lá

In [5]:
cv2.imshow("Frutas", imagem)
cv2.waitKey(0)
cv2.destroyAllWindows() 

Vamos acessar os pixels dessa imagem

In [6]:
valorPixel	= imagem[150,150]
print(valorPixel)

[103 118 120]


Observe	que foi	 retornado um vetor contendo três valores inteiros. Isso ocorre pois estamos trabalhando com uma imagem colorida, representada em RGB. Sendo assim, cada pixel possui três valores, referentes respectivamente à intensidade	de	vermelho verde e azul.

Mas agora, vamos converter nossa imagem para cinza e ver o que será retornado como valor, veja


In [7]:
imagem = cv2.cvtColor(imagem,cv2.COLOR_RGB2GRAY)
valorPixel = imagem[150,150]
print(valorPixel)

114


Obtemos uma valor único, observe que nesse caso, a imagem representada	em tons de cinza será um único valor inteiro, referente à intensidade de luz representada pelo pixel.

#### Alterando pixels
Para alterar o valor de um determinado pixel da imagem, basta realizar a operação inversa: atribuir novos valores a um determinado elemento da matriz. Veja o exemplo:

In [13]:
imagem = cv2.imread("/home/luiz/Documentos/MeusProjetos/Dicas_OpenCV/VisaoComp/Imagens/frutas3.jpg")
print(imagem[150,150]) 
imagem[150,150]	= [255,255,255]	
print(imagem[150,150])
cv2.imshow("Frutas", imagem)
cv2.waitKey(0)
cv2.destroyAllWindows() 

# Perceba que iremos colocar um ponto branco, que representa o vetor rgb de maior intensidade r: 255, g: 255, b: 255

[103 118 120]
[255 255 255]


### Quantos pixels tem numa imagem digital?

Para saber isso, podemos utilizador o métodO size no objeto do tipo numpy.ndarray, veja

In [4]:
imagem.size

2916000

Mas atenção, como nossa imagem está no formato RGB, temos três canais de cores, portando, precisamos dividir para encontrar o total de pixels dela.


2916000/3 = 972000.0 pixels

Agora você deve estar imaginando como deve ser o resultado de pixel para uma imagem em tons de cinza, correto, vamos ver na prática.


In [10]:
imagem = cv2.cvtColor(imagem, cv2.COLOR_RGB2GRAY)
imagem.size

972000

A imagem em tons de cinza tem apenas um canal que representanta cada pixel com uma intensidade, consequentemente, teremos sempre o valor real dos pixels quando utilizarmos a função size .