In [1]:
import numpy as np 


In [7]:
myarray = np.array([[[1,2],[1,2],[1,4]],
                    [[1,3],[1,5],[1,2]]])

In [8]:
myarray.shape

(2, 3, 2)

In [9]:
myarray[1][1][0] = 7

In [13]:
myarray.transpose()

array([[[1, 1],
        [1, 7],
        [1, 1]],

       [[2, 3],
        [2, 5],
        [4, 2]]])

In [14]:
myarray.shape

(2, 3, 2)

In [15]:
myarray

array([[[1, 2],
        [1, 2],
        [1, 4]],

       [[1, 3],
        [7, 5],
        [1, 2]]])

In [18]:
np.ones([2,2,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])